import {chromium} from 'playwright';import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {resolve,extname} from 'node:path';import {tmpdir} from 'node:os';import assert from 'node:assert/strict';
const root=resolve('dist'),art=resolve('test-artifacts');await mkdir(art,{recursive:true});
const cases=JSON.parse(await readFile(root+'/data/scenarios.json'));
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;const f=resolve(root,'.'+(path==='/'?'/index.html':path));if(!f.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.png':'image/png'})[extname(f)]||'application/octet-stream');res.end(await readFile(f))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
// Same browser lookup as browser.mjs: CHROMIUM_EXECUTABLE, else the Linux binary test:ui extracts, else Playwright's default.
const executablePath=process.env.CHROMIUM_EXECUTABLE||(process.platform==='linux'?resolve(tmpdir(),'room404-chromium'):undefined);
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const page=await context.newPage();page.setDefaultTimeout(8000);const errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.addInitScript(()=>{if(window.name.startsWith('{'))localStorage.setItem('404_active_v2',window.name)});await page.goto(url);await page.waitForFunction(()=>!document.getElementById('startStory').disabled);
 for(let i=0;i<cases.length;i++){
 const c=cases[i];await page.evaluate(async({id,i})=>{const {newRun}=await import('/engine.js');const v=await(await fetch('/data/visitors.json')).json(),a=await(await fetch('/data/anomalies.json')).json();const run=newRun('story',v,a,'2026-09-30');run.cases[0]={visitor:v[i].id,anomaly:id};window.name=JSON.stringify(run)},{id:c.id,i});
 await page.reload();await page.locator('#resume').click();assert.ok(await page.locator('#portrait .person-sprite').isVisible());
 await page.locator('[data-tool="CCTV"]').click();assert.equal(await page.locator('canvas').count(),0,'CCTV must not reveal before lookup');await page.locator('#toolAction').click();await page.waitForFunction(()=>document.querySelector('.replay-canvas')?.dataset.mode);
 for(let j=0;j<3;j++){await page.locator(`[data-chapter="${j}"]`).click();assert.equal(await page.locator('.replay-canvas').getAttribute('data-mode'),c.scenes[j].mode,c.id);assert.equal(await page.locator('.replay-canvas').getAttribute('data-location'),c.scenes[j].location,c.id);assert.match(await page.locator('.replay-caption').innerText(),new RegExp('장면 '+(j+1)));}
 if([0,30,33,35,60,70,78].includes(i)){await page.locator('[data-chapter="1"]').click();await page.screenshot({path:`${art}/case-${c.id}.png`,fullPage:true})}
 if(i===0||i===4){const seekTo=t=>page.evaluate(t=>{const s=document.querySelector('.replay-seek');s.value=t;s.dispatchEvent(new Event('input'))},t),frame=()=>page.locator('.replay-canvas').getAttribute('data-walk-frame');await seekTo(0.125);assert.equal(await frame(),i===0?'1':'-1','V001 only walk sheet');await seekTo(0.5);assert.equal(await frame(),i===0?'4':'-1','walk frame follows cursor');await seekTo(7);assert.equal(await frame(),'-1','no walk sheet while waiting')}
 if(i===0){await page.locator('[data-chapter="0"]').click();await page.locator('.replay-play').click();await page.waitForFunction(()=>Number(document.querySelector('.replay-seek').value)>.3);await page.locator('.replay-play').click();const pos=await page.locator('.replay-seek').inputValue();await page.waitForTimeout(150);assert.equal(await page.locator('.replay-seek').inputValue(),pos,'Pause must hold the frame')}
 await page.locator('#nextTool').click();await page.locator('#toolAction').click();while(!(await page.locator('.book-next').isDisabled()))await page.locator('.book-next').click();assert.equal(await page.locator('.record-pair section').count(),2);assert.ok((await page.locator('.record-pair').innerText()).includes(c.document.source));
 await page.locator('#nextTool').click();await page.locator('#toolAction').click();assert.ok(await page.locator('.transcript li').count()>=2);assert.ok((await page.locator('.call-record').innerText()).includes(c.call.state));
 await page.locator('#nextTool').click();assert.ok(!(await page.locator('#toolBody').innerText()).includes(c.verificationDetail));await page.locator('#toolAction').click();assert.ok((await page.locator('#toolBody').innerText()).includes(c.verificationDetail));
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),c.id+' horizontal overflow');await page.locator('#finishInspect').click();await page.locator(c.safe?'#allow':'#deny').click();assert.match(await page.locator('#feedbackTitle').innerText(),/맞았어요/);
 results.push({id:c.id,scenes:3,status:'PASS'});if((i+1)%10===0)console.log(`PASS ${i+1}/100 cases · ${(i+1)*3}/300 scenes`);
 }
 assert.deepEqual(errors,[]);console.log('PASS 100 cases / 300 scenes; all document, call, verification and decision flows; zero JS errors');
}catch(e){results.push({status:'FAIL',error:e.stack});process.exitCode=1;console.error(e)}finally{await writeFile(art+'/all-cases-results.json',JSON.stringify({timestamp:new Date().toISOString(),errors,results},null,2));await browser.close();server.close()}
