import {chromium,webkit} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {tmpdir} from 'node:os';
import {brotliDecompressSync} from 'node:zlib';
import assert from 'node:assert/strict';
const root=resolve('dist'),art=resolve('test-artifacts');await mkdir(art,{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.webmanifest':'application/manifest+json'};
let networkDisabled=false;
const server=createServer(async(req,res)=>{if(networkDisabled){req.socket.destroy();return}try{const url=new URL(req.url,'http://localhost'),file=resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',types[extname(file)]||'application/octet-stream');res.end(await readFile(file))}catch{res.statusCode=404;res.end('Not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
const results=[];let failed=false;
async function check(name,fn){try{await fn();results.push({test:name,status:'PASS'});console.log('PASS',name)}catch(e){failed=true;results.push({test:name,status:'FAIL',error:e.message});console.error('FAIL',name,e.message)}}
async function suite(browser,label){
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2}),page=await context.newPage(),errors=[];await context.addInitScript(()=>{window.__spoken=[];const synth={speak(u){window.__spoken.push({text:u.text,lang:u.lang,pitch:u.pitch});setTimeout(()=>u.onend&&u.onend(),5)},cancel(){},getVoices(){return[]}};Object.defineProperty(window,'speechSynthesis',{value:synth,configurable:true});window.SpeechSynthesisUtterance=function(t){this.text=t};});page.on('pageerror',e=>errors.push(e.message));
 await check(label+': launch and responsive layouts',async()=>{await page.goto(origin);await page.waitForFunction(()=>!document.getElementById('startStory').disabled);for(const width of [320,390,430,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)}await page.setViewportSize({width:390,height:844});await page.screenshot({path:art+`/${label}-home.png`,fullPage:true})});
 await check(label+': evidence saved across reload',async()=>{await page.locator('#startStory').click();assert.equal(await page.locator('#portrait .person-sprite').count(),1);assert.match(await page.locator('#routine').innerText(),/CCTV/);assert.doesNotMatch(await page.locator('#evidence').innerText(),/7분/);assert.ok(await page.locator('#verify').isDisabled());await page.locator('[data-tool="CCTV"]').click();await page.locator('#toolAction').click();await page.locator('#backDesk').click();await page.locator('#verify').click();await page.locator('#toolAction').click();await page.locator('#backDesk').click();await page.reload();await page.locator('#resume').click();assert.ok(await page.locator('[data-tool="CCTV"]').isEnabled());assert.match(await page.locator('#evidence').innerText(),/마지막 · 한 번 더 확인/);await page.screenshot({path:art+`/${label}-game.png`,fullPage:true})});
 await check(label+': investigation screens, read action, sequential flow and reopen',async()=>{
 await page.locator('[data-tool="CCTV"]').click();assert.ok(await page.locator('#investigation').isVisible());assert.ok(await page.locator('#game').isHidden());await page.waitForFunction(()=>document.querySelector('.replay-canvas')?.dataset.mode);assert.equal(await page.locator('.replay-canvas').getAttribute('data-count'),'1');await page.screenshot({path:art+`/${label}-cctv.png`,fullPage:true});
 await page.locator('#nextTool').click();assert.match(await page.locator('#toolTitle').innerText(),/주민·방문 기록/);assert.ok(await page.locator('.register table').isVisible());await page.locator('#toolAction').click();assert.equal(await page.locator('.book-count').innerText(),'1 / 4');assert.ok(await page.locator('.book-prev').isDisabled());await page.locator('.book-next').click();assert.equal(await page.locator('.book-count').innerText(),'2 / 4');const box=await page.locator('[data-book]').boundingBox();await page.mouse.move(box.x+box.width*.8,box.y+60);await page.mouse.down();await page.mouse.move(box.x+box.width*.2,box.y+60);await page.mouse.up();assert.equal(await page.locator('.book-count').innerText(),'3 / 4');await page.keyboard.press('ArrowLeft');await page.locator('[data-book]').focus();await page.keyboard.press('ArrowRight');await page.locator('.book-next').click();assert.ok(await page.locator('.book-next').isDisabled());assert.equal(await page.locator('.record-pair section').count(),2);await page.waitForTimeout(500);await page.screenshot({path:art+`/${label}-register.png`,fullPage:true});
 await page.locator('#nextTool').click();assert.match(await page.locator('#toolTitle').innerText(),/전화/);await page.evaluate(()=>{window.__spoken=[]});await page.locator('#toolAction').click();await page.waitForFunction(()=>window.__spoken.length>=2&&document.querySelector('.call-record').dataset.playing==='false');const lines=await page.locator('.transcript li').count();assert.equal(await page.evaluate(()=>window.__spoken.length),lines);assert.ok(await page.evaluate(()=>window.__spoken.every(u=>u.lang==='ko-KR')));assert.ok(new Set(await page.evaluate(()=>window.__spoken.map(u=>u.pitch))).size>=2,'speakers sound different');await page.locator('.call-sound').click();assert.equal(await page.locator('.call-sound').innerText(),'소리 꺼짐');await page.locator('.call-sound').click();await page.screenshot({path:art+`/${label}-call.png`,fullPage:true});await page.locator('#nextTool').click();await page.locator('#finishInspect').click();
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('404_active_v2')).seen.length),3);await page.locator('[data-tool="명부"]').click();assert.ok(await page.locator('#toolAction').isDisabled());for(const width of [320,390,430,768,1280]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}await page.setViewportSize({width:390,height:844});await page.keyboard.press('Escape');assert.ok(await page.locator('#game').isVisible());
 });
 await check(label+': eight cases, feedback resume, no duplicate decisions',async()=>{const choices=[true,false,true,false,true,false,true,false];for(let i=0;i<8;i++){for(const tool of ['명부','CCTV','통화']){const b=page.locator(`[data-tool="${tool}"]`);await b.click();if(!await page.locator('#toolAction').isDisabled())await page.locator('#toolAction').click();await page.locator('#backDesk').click()}await page.locator('#verify').click();if(!await page.locator('#toolAction').isDisabled())await page.locator('#toolAction').click();await page.locator('#backDesk').click();if(i===1){await page.locator('[data-tool="CCTV"]').click();await page.waitForFunction(()=>document.querySelector('.replay-canvas')?.dataset.time);assert.equal(await page.locator('.replay-canvas').getAttribute('data-time'),'00:37');await page.locator('[data-chapter="1"]').click();assert.equal(await page.locator('.replay-canvas').getAttribute('data-time'),'00:47');await page.locator('#backDesk').click();assert.match(await page.locator('.case-timeline li').first().innerText(),/이전 기록/)}await page.locator(choices[i]?'#allow':'#deny').click();if(i===0){await page.evaluate(()=>document.getElementById('allow').click());assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('404_active_v2')).history.length),1);await page.reload();await page.locator('#resume').click();assert.match(await page.locator('#feedbackTitle').innerText(),/맞았어요/)}await page.locator('#next').click()}assert.equal(await page.locator('#ending').innerText(),'신중한 경비원');assert.match(await page.locator('#stats').innerText(),/8명 중 8명 맞힘/);await page.screenshot({path:art+`/${label}-result.png`,fullPage:true})});
 await check(label+': PNG result export',async()=>{await page.evaluate(()=>{Object.defineProperty(navigator,'canShare',{value:()=>false,configurable:true})});await page.locator('#share').click();await page.locator('#shareImage').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('shareImage').naturalWidth===1080);assert.equal(await page.locator('#shareImage').evaluate(i=>i.naturalHeight),1350);const download=page.waitForEvent('download');await page.locator('#shareDownload').click();const file=await download;await file.saveAs(art+`/${label}-result-card.png`);await page.locator('#shareClose').click()});
 await check(label+': offline cold reload and continued gameplay',async()=>{await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);try{if(label==='webkit')networkDisabled=true;else await context.setOffline(true);await page.reload();await page.locator('#resume').click();assert.equal(await page.locator('#ending').innerText(),'신중한 경비원');await page.locator('#again').click();await page.locator('[data-tool="명부"]').click();await page.locator('#toolAction').click();await page.locator('#backDesk').click();assert.match(await page.locator('#evidence').innerText(),/방문할 집|그 집/)}finally{networkDisabled=false;await context.setOffline(false)}});
 await check(label+': corrupt save recovery',async()=>{await page.addInitScript(()=>localStorage.setItem('404_active_v2',JSON.stringify({version:'broken'})));await page.reload();await page.waitForFunction(()=>!document.getElementById('startStory').disabled);assert.ok(await page.locator('#resume').isHidden());assert.ok(await page.locator('#storageNotice').isVisible())});
 await check(label+': zero uncaught JavaScript errors',async()=>assert.deepEqual(errors,[]));await context.close();
 const isolated=await browser.newContext({serviceWorkers:'block'}),errorPage=await isolated.newPage();
 await check(label+': data failure and retry',async()=>{await errorPage.route('**/data/visitors.json',route=>route.fulfill({status:503,body:'unavailable'}));await errorPage.goto(origin);await errorPage.locator('#retry').waitFor({state:'visible'});assert.ok(await errorPage.locator('#startStory').isDisabled());await errorPage.unroute('**/data/visitors.json');await errorPage.locator('#retry').click();await errorPage.waitForFunction(()=>!document.getElementById('startStory').disabled)});await isolated.close();
}
try{
 let executablePath=process.env.CHROMIUM_EXECUTABLE;
 if(!executablePath&&process.platform==='linux'){
  executablePath=resolve(tmpdir(),'room404-chromium');
  const size=await stat(executablePath).then(s=>s.size).catch(()=>0);
  if(size<1000000)await writeFile(executablePath,brotliDecompressSync(await readFile('node_modules/@sparticuz/chromium/bin/chromium.br')),{mode:0o755});
 }
 const c=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});console.log('Chromium',await c.version());await suite(c,'chromium');await c.close();
 if(process.env.TEST_WEBKIT==='1'){const w=await webkit.launch({headless:true});console.log('WebKit',await w.version());await suite(w,'webkit');await w.close()}
}catch(e){failed=true;results.push({test:'browser infrastructure',status:'FAIL',error:e.message});console.error(e)}finally{server.close();await writeFile(art+'/browser-results.json',JSON.stringify({timestamp:new Date().toISOString(),results},null,2))}
if(failed)process.exitCode=1;
